// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sql_ledger.Data;

#nullable disable

namespace sqlledger.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240225153704_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("address_id");

            modelBuilder.HasSequence<int>("archive_id");

            modelBuilder.HasSequence<int>("assembly_id");

            modelBuilder.HasSequence<int>("contact_id");

            modelBuilder.HasSequence<int>("public_id")
                .StartsAt(10000L);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Acc_trans", b =>
                {
                    b.Property<decimal?>("Amount")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("amount");

                    b.Property<bool?>("Approved")
                        .HasColumnType("bit")
                        .HasColumnName("approved");

                    b.Property<int?>("ChartId")
                        .HasColumnType("int")
                        .HasColumnName("chart_id");

                    b.Property<DateTime?>("Cleared")
                        .HasColumnType("datetime2")
                        .HasColumnName("cleared");

                    b.Property<bool?>("FxTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("fx_transaction");

                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Memo")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("memo");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("source");

                    b.Property<DateTime?>("TransDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("transdate");

                    b.Property<int?>("TransId")
                        .HasColumnType("int")
                        .HasColumnName("trans_id");

                    b.Property<int?>("VrId")
                        .HasColumnType("int")
                        .HasColumnName("vr_id");

                    b.HasIndex("ChartId")
                        .HasDatabaseName("acc_trans_chart_id_key");

                    b.HasIndex("Source")
                        .HasDatabaseName("acc_trans_source_key");

                    b.HasIndex("TransDate")
                        .HasDatabaseName("acc_trans_transdate_key");

                    b.HasIndex("TransId")
                        .HasDatabaseName("acc_trans_trans_id_key");

                    b.ToTable("acc_trans", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.AcsRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR public_id");

                    b.Property<string>("Acs")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("acs");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<short?>("Rn")
                        .HasColumnType("smallint")
                        .HasColumnName("rn");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("acsrole_pkey");

                    b.ToTable("acsrole", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR address_id");

                    b.Property<string>("Address1")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("country");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("State")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("state");

                    b.Property<int?>("TransId")
                        .HasColumnType("int")
                        .HasColumnName("trans_id");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("zipcode");

                    b.HasKey("Id")
                        .HasName("address_pkey");

                    b.ToTable("address", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Ap", b =>
                {
                    b.Property<decimal?>("Amount")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("amount");

                    b.Property<bool?>("Approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("approved");

                    b.Property<int?>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("bank_id");

                    b.Property<float?>("CashDiscount")
                        .HasColumnType("real")
                        .HasColumnName("cashdiscount");

                    b.Property<string>("Curr")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("curr");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("datetime2")
                        .HasColumnName("datepaid");

                    b.Property<string>("Dcn")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("dcn");

                    b.Property<int?>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<short?>("DiscountTerms")
                        .HasColumnType("smallint")
                        .HasColumnName("discountterms");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("duedate");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<double?>("ExchangeRate")
                        .HasColumnType("float")
                        .HasColumnName("exchangerate");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR public_id");

                    b.Property<string>("IntNotes")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("intnotes");

                    b.Property<string>("InvNumber")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("invnumber");

                    b.Property<bool>("Invoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("invoice");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("language_code");

                    b.Property<decimal?>("NetAmount")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("netamount");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("notes");

                    b.Property<bool>("OnHold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("onhold");

                    b.Property<string>("OrdNumber")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("ordnumber");

                    b.Property<decimal?>("Paid")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("paid");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("paymentmethod_id");

                    b.Property<string>("PoNumber")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("ponumber");

                    b.Property<string>("QuoNumber")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("quonumber");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("ShipVia")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("shipvia");

                    b.Property<string>("ShippingPoint")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("shippingpoint");

                    b.Property<bool>("TaxIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("taxincluded");

                    b.Property<short>("Terms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("terms");

                    b.Property<string>("Till")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("till");

                    b.Property<DateTime>("TransDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("transdate")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int")
                        .HasColumnName("vendor_id");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_id");

                    b.Property<string>("WayBill")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("waybill");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ap_employee_id_key");

                    b.HasIndex("Id")
                        .HasDatabaseName("ap_id_key");

                    b.HasIndex("InvNumber")
                        .HasDatabaseName("ap_invnumber_key");

                    b.HasIndex("OrdNumber")
                        .HasDatabaseName("ap_ordnumber_key");

                    b.HasIndex("QuoNumber")
                        .HasDatabaseName("ap_quonumber_key");

                    b.HasIndex("TransDate")
                        .HasDatabaseName("ap_transdate_key");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ap_vendor_id_key");

                    b.ToTable("ap", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Ar", b =>
                {
                    b.Property<decimal?>("Amount")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("amount");

                    b.Property<bool?>("Approved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("approved");

                    b.Property<int?>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("bank_id");

                    b.Property<float?>("CashDiscount")
                        .HasColumnType("real")
                        .HasColumnName("cashdiscount");

                    b.Property<string>("Curr")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("curr");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("DatePaid")
                        .HasColumnType("datetime2")
                        .HasColumnName("datepaid");

                    b.Property<string>("Dcn")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("dcn");

                    b.Property<int?>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<short?>("DiscountTerms")
                        .HasColumnType("smallint")
                        .HasColumnName("discountterms");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("duedate");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<double?>("ExchangeRate")
                        .HasColumnType("float")
                        .HasColumnName("exchangerate");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR public_id");

                    b.Property<string>("IntNotes")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("intnotes");

                    b.Property<string>("InvNumber")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("invnumber");

                    b.Property<bool>("Invoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("invoice");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("language_code");

                    b.Property<decimal?>("NetAmount")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("netamount");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("notes");

                    b.Property<bool?>("OnHold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("onhold");

                    b.Property<string>("OrdNumber")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("ordnumber");

                    b.Property<decimal?>("Paid")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("paid");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("paymentmethod_id");

                    b.Property<string>("PoNumber")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("ponumber");

                    b.Property<string>("QuoNumber")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("quonumber");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ShipVia")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("shipvia");

                    b.Property<string>("ShippingPoint")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("shippingpoint");

                    b.Property<bool?>("TaxIncluded")
                        .HasColumnType("bit")
                        .HasColumnName("taxincluded");

                    b.Property<short>("Terms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("terms");

                    b.Property<string>("Till")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("till");

                    b.Property<DateTime>("TransDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("transdate")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_id");

                    b.Property<string>("WayBill")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("waybill");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ar_customer_id_key");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ar_employee_id_key");

                    b.HasIndex("Id")
                        .HasDatabaseName("ar_id_key");

                    b.HasIndex("InvNumber")
                        .HasDatabaseName("ar_invnumber_key");

                    b.HasIndex("OrdNumber")
                        .HasDatabaseName("ar_ordnumber_key");

                    b.HasIndex("QuoNumber")
                        .HasDatabaseName("ar_quonumber_key");

                    b.HasIndex("TransDate")
                        .HasDatabaseName("ar_transdate_key");

                    b.ToTable("ar", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Archive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR archive_id");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("filename");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("archive_pkey");

                    b.ToTable("archive", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.ArchiveData", b =>
                {
                    b.Property<int?>("ArchiveId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("archive_id");

                    b.Property<string>("Bt")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("bt");

                    b.Property<int?>("Rn")
                        .HasColumnType("int")
                        .HasColumnName("rn");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasIndex("ArchiveId");

                    b.ToTable("archivedata", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Assembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR assembly_id");

                    b.Property<bool?>("Adj")
                        .HasColumnType("bit")
                        .HasColumnName("adj");

                    b.Property<int?>("Aid")
                        .HasColumnType("int")
                        .HasColumnName("aid");

                    b.Property<bool?>("Bom")
                        .HasColumnType("bit")
                        .HasColumnName("bom");

                    b.Property<int?>("PartsId")
                        .HasColumnType("int")
                        .HasColumnName("parts_id");

                    b.Property<decimal?>("Qty")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("qty");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("assembly_id_key");

                    b.ToTable("assembly", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.AuditTrail", b =>
                {
                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("action");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("FormName")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("formname");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("reference");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("tablename");

                    b.Property<DateTime>("TransDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("transdate")
                        .HasDefaultValueSql("CAST(GETUTCDATE() AS Date)");

                    b.Property<int?>("TransId")
                        .HasColumnType("int")
                        .HasColumnName("trans_id");

                    b.HasIndex("TransId")
                        .HasDatabaseName("audittrail_trans_id_key");

                    b.ToTable("audittrail", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Bank", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("address_id")
                        .HasDefaultValueSql("NEXT VALUE FOR address_id");

                    b.Property<string>("Bic")
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("bic");

                    b.Property<string>("ClearingNumber")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("clearingnumber");

                    b.Property<string>("Dcn")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("dcn");

                    b.Property<string>("Iban")
                        .HasColumnType("nvarchar(34)")
                        .HasColumnName("iban");

                    b.Property<int?>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("MemberNumber")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("membernumber");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Rvc")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("rvc");

                    b.ToTable("bank", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Br", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR public_id");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("ApprDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("apprdate");

                    b.Property<string>("Batch")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("batch");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("batchnumber");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("managerid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("TransDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("transdate")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id")
                        .HasName("br_pkey");

                    b.ToTable("br", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Business", b =>
                {
                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<float?>("Discount")
                        .HasColumnType("real")
                        .HasColumnName("discount");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR public_id");

                    b.Property<int?>("Rn")
                        .HasColumnType("int")
                        .HasColumnName("rn");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.ToTable("business", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("TransId")
                        .HasColumnType("int")
                        .HasColumnName("trans_id");

                    b.Property<decimal?>("GrossWeight")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("grossweight");

                    b.Property<decimal?>("NetWeight")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("netweight");

                    b.Property<string>("Package")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("package");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<decimal?>("Volume")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("volume");

                    b.HasKey("Id", "TransId")
                        .HasName("cargo_id_key");

                    b.ToTable("cargo", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Chart", b =>
                {
                    b.Property<string>("AccNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("accno");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("char")
                        .HasColumnName("category");

                    b.Property<string>("ChartType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char")
                        .HasDefaultValue("A")
                        .HasColumnName("charttype");

                    b.Property<bool?>("Closed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("closed");

                    b.Property<bool?>("Contra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("contra");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<string>("GifiAccno")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("gifi_accno");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR public_id");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("link");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasIndex("AccNo")
                        .IsUnique()
                        .HasDatabaseName("chart_accno_key");

                    b.HasIndex("Category")
                        .HasDatabaseName("chart_category_key");

                    b.HasIndex("GifiAccno")
                        .HasDatabaseName("chart_gifi_accno_key");

                    b.HasIndex("Id")
                        .HasDatabaseName("chart_id_key");

                    b.HasIndex("Link")
                        .HasDatabaseName("chart_link_key");

                    b.ToTable("chart", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR contact_id");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("contacttitle");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("email");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fax");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("firstname");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char")
                        .HasDefaultValue("M")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("lastname");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mobile");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("occupation");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("Salutation")
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("salutation");

                    b.Property<int>("TransId")
                        .HasColumnType("int")
                        .HasColumnName("trans_id");

                    b.Property<string>("TypeOfContact")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("typeofcontact");

                    b.HasKey("Id")
                        .HasName("contact_pkey");

                    b.ToTable("contact", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Curr", b =>
                {
                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("curr");

                    b.Property<short?>("Prec")
                        .HasColumnType("smallint")
                        .HasColumnName("prec");

                    b.Property<short?>("Rn")
                        .HasColumnType("smallint")
                        .HasColumnName("rn");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Currency")
                        .HasName("curr_pkey");

                    b.ToTable("curr", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR public_id");

                    b.Property<int?>("ArapAccNoId")
                        .HasColumnType("int")
                        .HasColumnName("arap_accno_id");

                    b.Property<string>("Bcc")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("bcc");

                    b.Property<int?>("BusinessId")
                        .HasColumnType("int")
                        .HasColumnName("business_id");

                    b.Property<float?>("CashDiscount")
                        .HasColumnType("real")
                        .HasColumnName("cashdiscount");

                    b.Property<string>("Cc")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("cc");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("contact");

                    b.Property<decimal>("CreditLimit")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasDefaultValue(0m)
                        .HasColumnName("creditlimit");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("curr");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("customernumber");

                    b.Property<float?>("Discount")
                        .HasColumnType("real")
                        .HasColumnName("discount");

                    b.Property<int?>("DiscountAccNoId")
                        .HasColumnType("int")
                        .HasColumnName("discount_accno_id");

                    b.Property<short?>("DiscountTerms")
                        .HasColumnType("smallint")
                        .HasColumnName("discountterms");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("email");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("enddate");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("fax");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("notes");

                    b.Property<int?>("PaymentAccNoId")
                        .HasColumnType("int")
                        .HasColumnName("payment_accno_id");

                    b.Property<int?>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("paymentmethod_id");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("PrepaymentAccnoId")
                        .HasColumnType("int")
                        .HasColumnName("prepayment_accno_id");

                    b.Property<int?>("PriceGroupId")
                        .HasColumnType("int")
                        .HasColumnName("pricegroup_id");

                    b.Property<bool?>("RemittanceVoucher")
                        .HasColumnType("bit")
                        .HasColumnName("remittancevoucher");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("SicCode")
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("sic_code");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startdate");

                    b.Property<bool>("TaxIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("taxincluded");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("taxnumber");

                    b.Property<short>("Terms")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("terms");

                    b.Property<decimal?>("Threshold")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("threshold");

                    b.HasKey("Id")
                        .HasName("customer_pkey");

                    b.HasIndex("Contact")
                        .HasDatabaseName("customer_contact_key");

                    b.HasIndex("CustomerNumber")
                        .HasDatabaseName("customer_number_key");

                    b.HasIndex("Name")
                        .HasDatabaseName("customer_name_key");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.CustomerTax", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<int>("ChartId")
                        .HasColumnType("int")
                        .HasColumnName("chart_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("CustomerId", "ChartId")
                        .HasName("customer_tax_pkey");

                    b.HasIndex("ChartId");

                    b.ToTable("customertax", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Deduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR public_id");

                    b.Property<bool?>("AgeDob")
                        .HasColumnType("bit")
                        .HasColumnName("agedob");

                    b.Property<int?>("BaseDon")
                        .HasColumnType("int")
                        .HasColumnName("basedon");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("description");

                    b.Property<int?>("EmployeeAccnoId")
                        .HasColumnType("int")
                        .HasColumnName("employee_accno_id");

                    b.Property<decimal?>("EmployeePays")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("employeepays");

                    b.Property<int?>("EmployerAccnoId")
                        .HasColumnType("int")
                        .HasColumnName("employer_accno_id");

                    b.Property<decimal?>("EmployerPays")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("employerpays");

                    b.Property<short?>("FromAge")
                        .HasColumnType("smallint")
                        .HasColumnName("fromage");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<short?>("ToAge")
                        .HasColumnType("smallint")
                        .HasColumnName("toage");

                    b.HasKey("Id")
                        .HasName("deduction_pkey");

                    b.ToTable("deduction", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.DeductionRate", b =>
                {
                    b.Property<int>("TransId")
                        .HasColumnType("int")
                        .HasColumnName("trans_id");

                    b.Property<decimal?>("Above")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("above");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("amount");

                    b.Property<decimal?>("Below")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("below");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("rate");

                    b.Property<short?>("Rn")
                        .HasColumnType("smallint")
                        .HasColumnName("rn");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("TransId")
                        .HasName("deductionrate_pkey");

                    b.ToTable("deductionrate", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Tax", b =>
                {
                    b.Property<int>("ChartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("chart_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChartId"));

                    b.Property<decimal?>("Rate")
                        .HasPrecision(28, 6)
                        .HasColumnType("decimal(28,6)")
                        .HasColumnName("rate");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("taxnumber");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("validto");

                    b.HasKey("ChartId")
                        .HasName("tax_pkey");

                    b.ToTable("tax", (string)null);
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Vr", b =>
                {
                    b.Property<int?>("BrId")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("br_id");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEXT VALUE FOR public_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("TransId")
                        .HasColumnType("int")
                        .HasColumnName("trans_id");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("vouchernumber");

                    b.HasIndex("BrId");

                    b.ToTable("vr", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("sql_ledger.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("sql_ledger.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sql_ledger.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("sql_ledger.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sql_ledger.Data.Model.ArchiveData", b =>
                {
                    b.HasOne("sql_ledger.Data.Model.Archive", "Archive")
                        .WithMany()
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("archivedata_archive_id_fkey");

                    b.Navigation("Archive");
                });

            modelBuilder.Entity("sql_ledger.Data.Model.CustomerTax", b =>
                {
                    b.HasOne("sql_ledger.Data.Model.Tax", null)
                        .WithMany("CustomerTaxes")
                        .HasForeignKey("ChartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sql_ledger.Data.Model.Customer", null)
                        .WithMany("CustomerTaxes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Vr", b =>
                {
                    b.HasOne("sql_ledger.Data.Model.Br", "Br")
                        .WithMany()
                        .HasForeignKey("BrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vr_br_id_fkey");

                    b.Navigation("Br");
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Customer", b =>
                {
                    b.Navigation("CustomerTaxes");
                });

            modelBuilder.Entity("sql_ledger.Data.Model.Tax", b =>
                {
                    b.Navigation("CustomerTaxes");
                });
#pragma warning restore 612, 618
        }
    }
}
